document.write("<footer id=\"footer\" class=\"footer-v4\">");
document.write("        <div class=\"container\">");
document.write("            <!-- Logo -->");
document.write("            ");
document.write("            <!-- End Logo -->");
document.write("");
document.write("            <!-- Content -->");
document.write("            <div class=\"footer-v4-content\">");
document.write("                <div class=\"row\">");
document.write("");
document.write(" <div class=\"col-md-3 col-xs-6 xs-full-width\">");
document.write("                        <!-- Contacts -->");
document.write("                          ");
document.write("                        <div class=\"margin-b-20\">");
document.write("                            <h3 class=\"footer-v4-title\">Links<\/h3>");
document.write("                          ");
document.write("<a class=\"footer-v4-text\" href=\"\/\/self-publish.in\/index.html\">Home<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"\/\/self-publish.in\/plans.html\">Plans<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"\/\/self-publish.in\/services.html\">Services<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"\/\/self-publish.in\/process.html\">Process<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"\/\/self-publish.in\/portfolio.html\">Portfolio<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"\/\/self-publish.in\/distribution.html\">Distribution<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"\/\/store.self-publish.in\/\">Book Store<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"http:\/\/platform.self-publish.in\/\">Publishing Platform<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"royaltycalculator.html\">Royalty Calculator<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"\/\/self-publish.in\/faq.html\">FAQs<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"\/\/self-publish.in\/careers.html\">Careers<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"http:\/\/scholargram.com\" target=\"_blank\">ScholarGram<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"http:\/\/booksfundr.self-publish.in\">BooksFundr<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"\/\/self-publish.in\/blog\/index.html\">Blog<\/a><br>");
document.write("<a class=\"footer-v4-text\" href=\"\/\/self-publish.in\/giveaway.html\">Giveaway<\/a><br>"); 
document.write("<a class=\"footer-v4-text\" href=\"\/\/self-publish.in\/contact.html\">Contact<\/a>");
document.write("");
document.write("                        <\/div>");
document.write("");
document.write("                        <!-- End Contacts -->");
document.write("                    <\/div>");
document.write("");
document.write("                     <div class=\"col-md-5 col-xs-6 xs-full-width\">");
document.write("                        ");
document.write("                        <div class=\"margin-b-20\">");
document.write("                            <h3 class=\"footer-v4-title\">Get in touch<\/h3>");
document.write("                            <p class=\"footer-v4-text\">");
document.write("                                <strong>Email:<\/strong><br>");
document.write("contact@whitefalconpublishing.com<br>");
document.write("whitefalconpublish@gmail.com<br><br>");
document.write("<strong>Phone:<\/strong> +91-828-384-3446, +91-911-589-2986<br>");
document.write("");
document.write("                            <\/p>");
document.write("                        <\/div>");
document.write("                        <div class=\"margin-b-20\">");
document.write("                            <p class=\"footer-v4-text\">");
document.write("                                <strong>Registered Office:<\/strong>");
document.write("                                No. 335, Sector 48A, ");
document.write("                              Chandigarh - 160047, INDIA<br>");
document.write("                                <strong>Branch Office:<\/strong><\/strong>");
document.write("                                No. 8\/ST1, Savitry Towers, Sector-91, ");
document.write("                            Mohali - 140307<br>");
document.write("                             <strong>Android App:<\/strong>");
document.write("                            <a href='https:\/\/play.google.com\/store\/apps\/details?id=io.cordova.whitefalcon&hl=en&utm_source=global_co&utm_medium=prtnr&utm_content=Mar2515&utm_campaign=PartBadge&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1'><img alt='Get it on Google Play' src='https:\/\/play.google.com\/intl\/en_us\/badges\/images\/generic\/en_badge_web_generic.png'\/ width='40%'><\/a>");
document.write("                            ");

document.write("<br><br><section class=\"newsletter-v7-subscribe\"><div class=\"center-content-hor-align-sm\">");
document.write("                            <form id=\"subscribe-form\" action=\"#\" method=\"get\" class=\"subscribe-form input-group\">");
document.write("                                <input type=\"text\" class=\"form-control newsletter-v7-subscribe-form\" placeholder=\"Email Address\" name=\"entry.1640236631\" value=\"\" id=\"entry_1640236631\" required>");
document.write("                                <span class=\"input-group-btn\">");
document.write("                                    <button class=\"btn-base-bg btn-base-sm newsletter-v7-subscribe-btn\" type=\"submit\">Subscribe<\/button>");
document.write("                                <\/span>");
document.write("                            <\/form>");
document.write("                        <\/div></section>");

document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("");
document.write("                    <div class=\"col-md-4 col-xs-6 xs-full-width\">");
document.write("                        <!-- Contacts -->");
document.write("                        <center>");
document.write("                           <a href=\"\/\/self-publish.in\/index.html\" class=\"image image-full\"><img width=\"55%\" src=\"\/\/self-publish.in\/images\/logo.png\" alt=\"\"><\/a>");
document.write("                           <\/center>");
document.write("                        <div class=\"margin-b-20\">");
document.write("                        <center>");
document.write("                            <h3 class=\"footer-v4-text\"><br>White Falcon Publishing Solutions LLP<\/h3>");
document.write("                            <a href=\"\/\/self-publish.in\/white-falcon-publishing-iso-certificate.html\"><p class=\"footer-v4-text\">An ISO 9001:2015 Certified Company<\/p></a><br>");
document.write("                            <a href=\"\/\/self-publish.in\/white-falcon-publishing-iso-certificate.html\"><img width=\"80%\" src=\"\/\/self-publish.in\/images\/iso.png\" alt=\"\"></a><br><br>");
document.write("                            <a href=\"https:\/\/www.google.com\/partners\/#i_profile;idtf=109514991320547753767\" target=\"_blank\"><img width=\"40%\" src=\"\/\/self-publish.in\/images\/Partnerbadge.jpg\" alt=\"\"></a>");
document.write("                            <\/center>");
document.write("                        <\/div>");
document.write("                        ");
document.write("                        ");
document.write("");
document.write("                        <!-- End Contacts -->");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!--\/\/ end row -->");
document.write("            <\/div>");
document.write("            <!-- End Content -->");
document.write("");
document.write("            <!-- Copyright -->");
document.write("            <div class=\"footer-v4-copyright\">");
document.write("                <div class=\"row\">");
document.write("                    <div class=\"col-sm-5 sm-margin-b-30\">");
document.write("                        <p class=\"footer-v4-copyright-text\">Copyright &#169; 2018 White Falcon Publishing Solutions LLP. <br>");
document.write("                        All Rights Reserved.<\/p>");
document.write("                    <\/div>");
document.write("                    <div class=\"col-sm-3 sm-margin-b-30\">");
document.write("                        <!-- Theme Icons White Background -->");
document.write("                        <ul class=\"list-inline text-center ul-li-lr-2 margin-b-0\">");
document.write("                            <li class=\"theme-icons-wrap\"><a href=\"\/\/facebook.com\/whitefalconpublishing\"><i class=\"theme-icons theme-icons-white-bg theme-icons-xs radius-circle fa fa-facebook\"><\/i><\/a><\/li>");
document.write("                            <li class=\"theme-icons-wrap\"><a href=\"https:\/\/twitter.com\/WhiteFalconpub\"><i class=\"theme-icons theme-icons-white-bg theme-icons-xs radius-circle fa fa-twitter\"><\/i><\/a><\/li>");
document.write("                            <li class=\"theme-icons-wrap\"><a href=\"https:\/\/plus.google.com\/116649724837582317540\/posts\"><i class=\"theme-icons theme-icons-white-bg theme-icons-xs radius-circle fa fa-google-plus\"><\/i><\/a><\/li>");
document.write("                        <\/ul>");
document.write("                        <!-- ENd Theme Icons White Background -->");
document.write("                    <\/div>");
document.write("                    <div class=\"col-sm-4\">");
document.write("                        <!-- Terms List -->");
document.write("                        <ul class=\"list-inline footer-v4-terms-list\">");
document.write("                            <li class=\"footer-v4-terms-item\"><a class=\"footer-v4-terms-link\" href=\"\/\/self-publish.in\/terms.html\">Terms &amp; Conditions<\/a><\/li>");
document.write("                            <li class=\"footer-v4-terms-item\"><a class=\"footer-v4-terms-link\" href=\"\/\/self-publish.in\/privacy.html\">Privacy &amp; Policy<\/a><\/li>");
document.write("                        <\/ul>");
document.write("                        <!-- End Terms List -->");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("            <\/div>");
document.write("            <!-- End Copyright -->");
document.write("        <\/div>");
document.write("    <\/footer>");
document.write("   <!-- Modal -->");
document.write("                <div class=\"modal fade\" id=\"subscribeModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\">");
document.write("                    <div class=\"modal-dialog\" role=\"document\">");
document.write("                        <div class=\"modal-content\">");
document.write("                            <div class=\"modal-header\">");
document.write("                                <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;<\/span><\/button>");
document.write("                                <h4 class=\"modal-title\" id=\"myModalLabel\">Thank you<\/h4>");
document.write("                            <\/div>");
document.write("                            <div class=\"modal-body\">");
document.write("                                <p>Thank you for subscribing to White Falcon Publishing newsletter.<\/p>");
document.write("                            <\/div>");
document.write("                            <div class=\"modal-footer\">");
document.write("                                <button type=\"button\" class=\"btn-dark-brd btn-base-sm radius-3 margin-r-10\" data-dismiss=\"modal\">Close<\/button>");
document.write("                            <\/div>");
document.write("                        <\/div>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!-- End Modal -->");
document.write("<script type=\"text\/javascript\" src=\"https:\/\/self-publish.in\/js\/formsubmit.js\"><\/script>");
