document.write('<a href="http://self-publish.in/index.html" class="image image-full"><img src="http://self-publish.in/images/logo.png" height="90px" alt=""></a>');
document.write('<nav id="nav">');
document.write('<a href="http://self-publish.in/index.html">Home</a>');
document.write('<a href="http://self-publish.in/plans.html">Plans</a>');
document.write('<a href="http://self-publish.in/services.html">Services</a>');
document.write('<a href="http://self-publish.in/process.html">Process</a>');
document.write('<a href="http://self-publish.in/distribution.html">Distribution</a>');
document.write('<a href="http://store.self-publish.in">Book Store</a>');
document.write('<a href="http://platform.self-publish.in" target="_blank">Platform</a>');
document.write('<a href="http://self-publish.in/royaltycalculator.html">Royalty Calculator</a>');
document.write('<a href="http://self-publish.in/faq.html">FAQ</a>');
document.write('<a href="http://self-publish.in/contact.html">Contact</a>');
document.write('</nav>');
