document.write("<header class=\"header-transparent header-transparent-bb navbar-fixed-top header-sticky\">    ");
document.write("        <!-- Navbar -->");
document.write("        <nav class=\"navbar mega-menu\" role=\"navigation\">");
document.write("            <div class=\"container\">");
document.write("                <!-- Brand and toggle get grouped for better mobile display -->");
document.write("                <div class=\"menu-container\">");
document.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".nav-collapse\">");
document.write("                        <span class=\"sr-only\">Toggle navigation<\/span>");
document.write("                        <span class=\"toggle-icon\"><\/span>");
document.write("                    <\/button>");
document.write("");
document.write("                    ");
document.write("");
document.write("                    <!-- Logo -->");
document.write("                    <div class=\"navbar-logo\">");
document.write("                        <a class=\"navbar-logo-wrap\" href=\"\/\/self-publish.in\/index.html\">");
document.write("                            <img class=\"navbar-logo-img navbar-logo-img-white\" class=\"navbar-logo-img\" src=\"\/\/self-publish.in\/images\/logo.png\" alt=\"White Falcon Publishing\">");
document.write("                            <img class=\"navbar-logo-img navbar-logo-img-dark\" src=\"\/\/self-publish.in\/images\/logo-black.png\" alt=\"Ark\">");
document.write("");
document.write("                        <\/a>");
document.write("                    <\/div>");
document.write("                    <!-- End Logo -->");
document.write("                <\/div>");
document.write("");
document.write("                <!-- Collect the nav links, forms, and other content for toggling -->");
document.write("                <div class=\"collapse navbar-collapse nav-collapse\">");
document.write("                    <div class=\"menu-container\">");
document.write("                        <ul class=\"nav navbar-nav\">");
document.write("                            <!-- Home -->");
document.write("                            <li class=\"nav-item dropdown\">");
document.write("                                <a class=\"nav-item-child radius-3\" href=\"\/\/self-publish.in\/index.html\" >");
document.write("                                    Home");
document.write("                                <\/a>");
document.write("                            <\/li>");
document.write("");
document.write("                             <li class=\"nav-item dropdown\">");
document.write("                                <a class=\"nav-item-child radius-3\" href=\"\/\/self-publish.in\/plans.html\" >");
document.write("                                    Plans");
document.write("                                <\/a>");
document.write("                            <\/li>");
document.write("");
document.write("                             <li class=\"nav-item dropdown\">");
document.write("                                <a class=\"nav-item-child radius-3\" href=\"\/\/self-publish.in\/services.html\" >");
document.write("                                    Services");
document.write("                                <\/a>");
document.write("                            <\/li>");
document.write("");
document.write("");
document.write("                             <li class=\"nav-item dropdown\">");
document.write("                                <a class=\"nav-item-child radius-3\" href=\"\/\/self-publish.in\/distribution.html\" >");
document.write("                                    Distribution");
document.write("                                <\/a>");
document.write("                            <\/li>");
document.write("");
document.write("                             <li class=\"nav-item dropdown\">");
document.write("                                <a class=\"nav-item-child radius-3\" href=\"\/\/store.self-publish.in\">");
document.write("                                    Book Store");
document.write("                                <\/a>");
document.write("                            <\/li>");
document.write("");
document.write("                             <li class=\"nav-item dropdown\">");
document.write("                                <a class=\"nav-item-child radius-3\" href=\"\/\/self-publish.in\/royaltycalculator.html\">");
document.write("                                    Royalty Calculator");
document.write("                                <\/a>");
document.write("                            <\/li>");
document.write("                            <li class=\"nav-item dropdown\">");
document.write("                                <a class=\"nav-item-child dropdown-toggle radius-3\" href=\"javascript:void(0);\" data-toggle=\"dropdown\">");
document.write("                                    Resources");
document.write("                                <\/a>");
document.write("                                <ul class=\"dropdown-menu\">");
document.write("                                    <!-- Default -->");
document.write("                                 <li class=\"dropdown-menu-item\"><a class=\"dropdown-menu-item-child\" href=\"\/\/self-publish.in\/process.html\">Publishing Process<\/a><\/li>");
document.write("                                  <li class=\"dropdown-menu-item\"><a class=\"dropdown-menu-item-child\" href=\"\/\/self-publish.in\/faq.html\">FAQ<\/a><\/li>");
document.write("                                   <li class=\"dropdown-menu-item\"><a class=\"dropdown-menu-item-child\" href=\"\/\/platform.self-publish.in\/\">Platform<\/a><\/li>");
document.write("                                   <li class=\"dropdown-menu-item\"><a class=\"dropdown-menu-item-child\" href=\"\/\/booksfundr.self-publish.in\/\">BooksFundr<\/a><\/li>");
document.write("                                   <li class=\"dropdown-menu-item\"><a class=\"dropdown-menu-item-child\" href=\"\/\/scholargram.com\/\">ScholarGram<\/a><\/li>");
document.write("                                   <li class=\"dropdown-menu-item\"><a class=\"dropdown-menu-item-child\" href=\"\/\/self-publish.in\/blog\/index.html\">Blog<\/a><\/li>");
document.write("                                   <li class=\"dropdown-menu-item\"><a class=\"dropdown-menu-item-child\" href=\"\/\/self-publish.in\/giveaway.html\">Giveaway<\/a><\/li>");
document.write("                                    ");
document.write("                                    <\/ul>");
document.write("                                <\/a>");
document.write("                            <\/li>");
document.write("");
document.write("");
document.write("                            <li class=\"nav-item dropdown\">");
document.write("                                <a class=\"nav-item-child radius-3\" href=\"\/\/self-publish.in\/contact.html\">");
document.write("                                    Contact");
document.write("                                <\/a>");
document.write("                            <\/li>");
document.write("                            <!-- ");
document.write("                            End Home -->");
document.write("");
document.write("                            ");
document.write("                        <\/ul>");
document.write("                    <\/div>");
document.write("                <\/div>");
document.write("                <!-- End Navbar Collapse -->");
document.write("            <\/div>");
document.write("            <!--\/\/ End Container-->");
document.write("        <\/nav>");
document.write("        <!-- Navbar -->");
document.write("    <\/header>");
