document.write("<!--Timeline v2 -->");
document.write("                            <ul class=\"timeline-v2\">");
document.write("                                <li class=\"timeline-v2-list-item\">");
document.write("                                    <i class=\"timeline-v2-badge-icon radius-circle fa fa-comments-o\"><\/i>");
document.write("                                    <small class=\"timeline-v2-news-date\">Jul 16, 2018<\/small>");
document.write("                                    <h5 class=\"timeline-v2-news-title\"><a href=\"Blog-Traditional-Publishing-Vs-Self-Publishing.html\">Traditional Publishing Versus Self-Publishing<\/a><\/h5>");
document.write("                                <\/li>");
document.write("                                <li class=\"timeline-v2-list-item\">");
document.write("                                    <i class=\"timeline-v2-badge-icon radius-circle fa fa-comments-o\"><\/i>");
document.write("                                    <small class=\"timeline-v2-news-date\">Aug 24, 2017<\/small>");
document.write("                                    <h5 class=\"timeline-v2-news-title\"><a href=\"Blog-latest-books-on-time-travel.html\">Latest Books on Time Travel<\/a><\/h5>");
document.write("                                <\/li>");
document.write("                                <li class=\"timeline-v2-list-item\">");
document.write("                                    <i class=\"timeline-v2-badge-icon radius-circle fa fa-comments-o\"><\/i>");
document.write("                                    <small class=\"timeline-v2-news-date\">Jun 14, 2017<\/small>");
document.write("                                    <h5 class=\"timeline-v2-news-title\"><a href=\"Blog-Writing-Style.html\">Writing Style<\/a><\/h5>");
document.write("                                <\/li>");
document.write("                                <li class=\"timeline-v2-list-item\">");
document.write("                                    <i class=\"timeline-v2-badge-icon radius-circle fa fa-comments-o\"><\/i>");
document.write("                                    <small class=\"timeline-v2-news-date\">Apr 18, 2017<\/small>");
document.write("                                    <h5 class=\"timeline-v2-news-title\"><a href=\"Blog-What-Should-I-Read.html\">What Should I Read? <\/a><\/h5>");
document.write("                                <\/li>");
document.write("                                <li class=\"timeline-v2-list-item\">");
document.write("                                    <i class=\"timeline-v2-badge-icon radius-circle fa fa-comments-o\"><\/i>");
document.write("                                    <small class=\"timeline-v2-news-date\">Mar 29, 2017<\/small>");
document.write("                                    <h5 class=\"timeline-v2-news-title\"><a href=\"Blog-Writers-Space-Time-Continuum.html\">Writer's Space Time Continuum<\/a><\/h5>");
document.write("                                <\/li>");
document.write("                                <li class=\"timeline-v2-list-item\">");
document.write("                                    <i class=\"timeline-v2-badge-icon radius-circle fa fa-comments-o\"><\/i>");
document.write("                                    <small class=\"timeline-v2-news-date\">Mar 16, 2017<\/small>");
document.write("                                    <h5 class=\"timeline-v2-news-title\"><a href=\"Blog-Challenges-faced-by-a-first-time-writer.html\">Challenges faced by a first time writer<\/a><\/h5>");
document.write("                                <\/li>");
document.write("                                <li class=\"timeline-v2-list-item\">");
document.write("                                    <i class=\"timeline-v2-badge-icon radius-circle fa fa-comments-o\"><\/i>");
document.write("                                    <small class=\"timeline-v2-news-date\">Feb 10, 2017<\/small>");
document.write("                                    <h5 class=\"timeline-v2-news-title\"><a href=\"Blog_Writer.html\">Writer?<\/a><\/h5>");
document.write("                                <\/li>");

document.write("                                <li class=\"timeline-v2-list-item\">");
document.write("                                    <i class=\"timeline-v2-badge-icon radius-circle fa fa-comments-o\"><\/i>");
document.write("                                    <small class=\"timeline-v2-news-date\">Oct 14, 2017<\/small>");
document.write("                                    <h5 class=\"timeline-v2-news-title\"><a href=\"Blog-Dos-and-Don'ts-for-a-First-time-Author.html\">Dos and Don'ts for a First-time Author<\/a><\/h5>");
document.write("                                <\/li>");

document.write("                                <li class=\"timeline-v2-list-item\">");
document.write("                                    <i class=\"timeline-v2-badge-icon radius-circle fa fa-comments-o\"><\/i>");
document.write("                                    <small class=\"timeline-v2-news-date\">Sep 16, 2017<\/small>");
document.write("                                    <h5 class=\"timeline-v2-news-title\"><a href=\"Blog-Revive-your-book-sales.html\">Revive your book sales<\/a><\/h5>");
document.write("                                <\/li>");

document.write("                                <li class=\"timeline-v2-list-item\">");
document.write("                                    <i class=\"timeline-v2-badge-icon radius-circle fa fa-comments-o\"><\/i>");
document.write("                                    <small class=\"timeline-v2-news-date\">Dec 10, 2015<\/small>");
document.write("                                    <h5 class=\"timeline-v2-news-title\"><a href=\"Blog-How-to-use-100-print-books-to-promote-self-published-books-in-the-best-possible-way.html\">How to use 100 print books to promote self-published books in the best possible way<\/a><\/h5>");
document.write("                                <\/li>");

document.write("                                <li class=\"timeline-v2-list-item\">");
document.write("                                    <i class=\"timeline-v2-badge-icon radius-circle fa fa-comments-o\"><\/i>");
document.write("                                    <small class=\"timeline-v2-news-date\">May 12, 2015<\/small>");
document.write("                                    <h5 class=\"timeline-v2-news-title\"><a href=\"Blog-Book-Launch-Events-to-Engage-Readers-&-Drive-Sales.html\">Book Launch Events to Engage Readers & Drive Sales<\/a><\/h5>");
document.write("                                <\/li>");

document.write("                                <li class=\"timeline-v2-list-item\">");
document.write("                                    <i class=\"timeline-v2-badge-icon radius-circle fa fa-comments-o\"><\/i>");
document.write("                                    <small class=\"timeline-v2-news-date\">Apr 08, 2015<\/small>");
document.write("                                    <h5 class=\"timeline-v2-news-title\"><a href=\"Blog-Benefits-of-Self-Publishing-over-Traditional-Publishing.html\">Benefits of Self Publishing over Traditional Publishing<\/a><\/h5>");
document.write("                                <\/li>");

document.write("                                <li class=\"clearfix\" style=\"float: none;\"><\/li>");
document.write("                            <\/ul>");
document.write("                            <!-- End Timeline v2 -->");
